// Verifies the live 3D hero: loads, reacts to pointer, camera moves on scroll.
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const [url, out] = process.argv.slice(2);
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 760 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
await page.goto(url);
await page.waitForFunction(() => document.querySelector('[data-hero]').classList.contains('is-3d'), null, { timeout: 120000 });
await page.waitForTimeout(3000);
const cam = () => page.evaluate(() => { const c = window.FORMA.hero.camera; return [c.position.x, c.position.y, c.position.z].map((v) => +v.toFixed(3)); });
const c0 = await cam();
await page.screenshot({ path: out + '/hero-a.png', timeout: 120000 });
await page.mouse.move(1200, 150, { steps: 5 });
await page.waitForTimeout(3000);
const c1 = await cam();
await page.screenshot({ path: out + '/hero-b.png', timeout: 120000 });
await page.evaluate(() => window.scrollTo(0, innerHeight * 0.6));
await page.waitForTimeout(4000);
const c2 = await cam();
await page.screenshot({ path: out + '/hero-c.png', timeout: 120000 });
const running = await page.evaluate(() => window.FORMA.hero.running);
await page.evaluate(() => window.scrollTo(0, document.querySelector('#services').offsetTop + 2000));
await page.waitForTimeout(8000);
const stopped = await page.evaluate(() => ({ paused: !window.FORMA.hero.running, y: scrollY, heroBottom: document.querySelector('[data-hero]').getBoundingClientRect().bottom }));
console.log({ c0, c1, c2, runningInHero: running, pausedOffscreen: stopped, ornaments: await page.evaluate(() => (window.FORMA.ornaments || []).length) });
console.log(errors.length ? errors.join('\n') : 'no errors');
await browser.close();
